name: deploy-github-pages

on: 
  repository_dispatch:
    types:
      - deploy-github-page

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hypersql/postgresql-knowledge-src
          token: ${{ secrets.ADMIN_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build and Deploy Gatsby
        run: |
          yarn install
          yarn gatsby build --prefix-paths
          git config user.name = ${{ secrets.ADMIN_USERNAME }}
          git config user.email = ${{ secrets.ADMIN_USER_EMAIL }}
          git remote set-url origin git@github.com:hypersql/postgresql-knowledge.git
          yarn gh-pages -r http://github.com/hypersql/postgresql-knowledge \
                        -d public -b gh-pages
