name: deploy-github-pages

on: 
  repository_dispatch:
    types:
      - deploy-github-page

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ADMIN_SSH_KEY }}
      
      - uses: actions/checkout@v2
        with:
          repository: hypersql/postgresql-knowledge-src
          ssh-key: ${{ secrets.ADMIN_SSH_KEY }}
          
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Gatsby
        run: |
          yarn install
          yarn gatsby build --prefix-paths
  
      - name: Deploy Gatsby
        run: |
          git config user.name = ${{ secrets.ADMIN_USERNAME }}
          git config user.email = ${{ secrets.ADMIN_USER_EMAIL }}
          yarn gh-pages -r http://github.com/hypersql/postgresql-knowledge -d public -b gh-pages
